---
- name: Install Apache
  package: #Universal package manager for Ansible.
    name: "{{ apache_package }}" #Created a variable so we can install the Apache service to all machines, including the Ubuntu machine as well.
    state: present

- name: Start and enable Apache
  service:
    name: "{{ apache_service }}" #Variable for Apache in Amazon Linux 2 and Ubuntu
    state: started
    enabled: true

- name: Deploy custom index.html to document root
  copy: 
    src: index.html
    dest: /var/www/html/index.html #This is the roor document for Apache
    owner: "{{ user_apache }}"
    group: "{{ group_apache }}"
    mode: '0644'