---
- name: Install Apache 
  hosts: Dev 
  become: yes 

  tasks:
    - name: Install httpd package
      yum:
        name: httpd 
        state: latest 

    - name: Start the httpd service
      service: 
        name: httpd
        state: started
        enabled: yes

    - name: Update HTML file
      lineinfile:
        path: /var/www/html/index.html
        create: yes
        line: This is part of the assignment 13-1.
        state: present