---
- name: Set up an HTTP web page
  hosts: all  
  become: yes  

  tasks:
    - name: Install Apache web server
      yum:
        name: httpd
        state: present

    - name: Create index.html with content
      copy:
        dest: /var/www/html/index.html
        content: "I created this with Ansible"
        owner: apache
        group: apache
        mode: '0644'

    - name: Ensure Apache is running and enabled
      service:
        name: httpd
        state: started
        enabled: yes
