---
- name: Create dev-report file on Dev servers
  hosts: Dev
  become: yes  

  tasks:
    - name: Create dev-report file with 777 permissions
      file:
        path: /tmp/dev-report
        state: touch
        mode: '0777'
        owner: James
        group: James

    - name: Add a line to dev-report file
      lineinfile:
        path: /tmp/dev-report
        line: "This is my test to add a new line to file with a Ansible Playbook"
        state: present
