---
- name: Create a user and a file in home directory
  hosts: all
  become: yes 

  tasks:
    - name: Create user James
      user:
        name: James

    - name: Create jamesfile in James's home directory
      file:
        path: /home/James/jamesfile
        state: touch
        owner: James
        group: James
        mode: '0644'
