---
- name: Set up http website
  hosts: Dev
  become: yes
  vars_files:
    - my_variables.yaml
  
  tasks:
    - name: Install httpd
      dnf:
        state: latest
        name: "{{ httpd_package }}"

    - name: Start the httpd service
      service: 
        name: "{{ httpd_service }}"
        state: started
        enabled: yes

    - name: Update HTML file
      lineinfile:
        path: /var/www/html/index.html
        create: yes
        line: What ever you want this is my website. I created this with Ansible
        state: present
