---
- name: Yum Playbook
  hosts: all
  become: yes

  tasks:
  - name: Install Firewalld
    yum:
      name: firewalld
      state: present

  - name: Install http
    yum:
      name: httpd
      state: latest