---
- name: Setup Nginx Web Server
  hosts: web_servers
  become: yes

  tasks:
    - name: Install Nginx on Amazon Linux 2
      when: ansible_distribution == "Amazon"  #This condition checks if the target host is running Amazon Linux. If true, the task will execute.
      yum:
        name: nginx.conf
        state: latest

    - name: Install Nginx on Ubuntu
      when: ansible_distribution == "Ubuntu"  #This condition checks if the target host is running Ubuntu. If true, the task will execute.
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
